
keywords: ["Aground", "Barge", "Capsized", "Coast guard", "Collision", "Crew", "Dock", "Drydock", "Engine-room", "Explosion",
"Ferry", "Fire", "Grounded", "Oilrig", "Pipeline", "Piracy", "Platform", "Pollution", "Refinery", "Salvage", "Sank",
"Ship", "Shipyard", "Sinking", "Strike", "Sunk", "Tanker", "Towage", "Tug", "Vessel", "Yacht"]
